FROM thebigdataguru/angular-cli:node.13.5.0-alpine-angular.8.3.21

ENV AWSCLI_VERSION "1.16.309"

RUN apk add --update \
    python \
    python-dev \
    py-pip \
    build-base \
    && pip install awscli==$AWSCLI_VERSION \
    && apk --purge -v del py-pip \
    && rm -rf /var/cache/apk/*
